{
 "title": "New PROD_DASHBOARD",
 "description": "PRIMARY",
 "time": { "from": "now-2d", "to": "now" },
 "panels": [
  { "title": "Critical Alerts", "type": "alertlist", "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 } },
  { "title": "CPU and DISK", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "M1 Disk Space Usage Change Rate:",
   "type": "stat",
   "description": "This detects the rate of change in disk space usage on host m1 over the past 2 hours.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "deriv(tigergraph_diskspace_usage{host_id=\"m1\"}[2h])\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average Memory Usage for Active Services",
   "type": "stat",
   "description": "This query computes the average memory usage for each active service (excluding the total node usage).",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(tigergraph_memory_usage{service_name!=\"\"}) by (service_name)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "M1 Network Traffic Rate Over Time per-second over past hour:",
   "type": "stat",
   "description": "This query calculates the per-second rate of incoming network traffic for host m1 over the past hour.\n",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(tigergraph_network_traffic{direction=\"incoming\", host_id=\"m1\"}[1h])\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "TG Cluster RAM Usage in MB",
   "type": "timeseries",
   "description": "Set Threshold below based on you server actual memory side ie 90% percent of 8gb is 7.2gb in MB is 7200mb",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    { "expr": "tigergraph_memory_usage{}", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Cluster CPU Usage %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    { "expr": "tigergraph_cpu_usage{}", "legendFormat": "__auto" }
   ]
  },
  { "title": "Overall System Health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "CPU PER NODE",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tigergraph_cpu_usage{service_name=\"\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RAM PER NODE",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tigergraph_memory_usage{service_name=\"\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 41 }, "options": { "content": "# Disk Space of TG" } },
  {
   "title": "M1 - Usage Capacity",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(tigergraph_diskspace_usage{host_id=~\"m1\"}) / (tigergraph_diskspace_free{host_id=~\"m1\"} + tigergraph_diskspace_usage{host_id=~\"m1\"}) * 100\n",
     "legendFormat": "__auto"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 51 }, "options": { "content": "# Network Stats of TG" } },
  {
   "title": "Cluster Network Traffic Incoming",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 53 },
   "targets": [
    {
     "expr": "tigergraph_network_traffic{direction=\"incoming\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cluster Network Traffic Outgoing",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 53 },
   "targets": [
    {
     "expr": "{direction=\"outgoing\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "TG Cluster Network Connections",
   "type": "timeseries",
   "description": "Set Threshold below based on you server actual memory side ie 90% percent of 8gb is 7.2gb in MB is 7200mb",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 53 },
   "targets": [
    {
     "expr": "tigergraph_network_connections{}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Peak QPS (Queries Per Second) for Specific Endpoints:",
   "type": "stat",
   "description": "This shows the peak queries per second for specified endpoints over the last day.\n\n",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max_over_time(tigergraph_qps{endpoint=~\"POST /restppkafkaloader/{graph_name}|GET /endpoints/{graph_name}\"}[1d])\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Number of Requests with High Latency over 1000 milliseconds ",
   "type": "stat",
   "description": "This query calculates the total number of requests in the RESTPP service where the maximum latency exceeded 1000 ms. It sums up the instances where the latency, as measured by the max_latency statistic, is greater than 1000 milliseconds across all endpoints.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(tigergraph_endpoint_latency{statistic=\"max_latency\", service_name=\"RESTPP\", endpoint=~\".*\"} > 1000)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Service Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 69 } },
  { "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 70 }, "options": { "content": "# Service Status of TG" } },
  {
   "title": "GPE STATUS Primary",
   "type": "stat",
   "description": "GPE status on Prod Pimary cluster",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 72 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "tigergraph_service_status{service_name=\"GPE\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "GPE STATUS Primary",
   "type": "stat",
   "description": "GPE status on Prod Pimary cluster",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 72 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "tigergraph_service_status{service_name=\"GPE\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "GSE STATUS Primary",
   "type": "stat",
   "description": "GPE status on Prod Pimary cluster",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 77 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "tigergraph_service_status{service_name=\"GSE\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Kafka STATUS Primary",
   "type": "stat",
   "description": "GPE status on Prod Pimary cluster",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 82 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "tigergraph_service_status{service_name=\"KAFKA\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "GSQL STATUS Primary",
   "type": "stat",
   "description": "GPE status on Prod Pimary cluster",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 87 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "tigergraph_service_status{service_name=\"GSQL\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "GUI STATUS Primary",
   "type": "stat",
   "description": "GPE status on Prod Pimary cluster",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 92 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "tigergraph_service_status{service_name=\"GUI\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "ETCD STATUS Primary",
   "type": "stat",
   "description": "GPE status on Prod Pimary cluster",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 97 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "tigergraph_service_status{service_name=\"ETCD\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "NGINX STATUS Primary",
   "type": "stat",
   "description": "GPE status on Prod Pimary cluster",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 102 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "tigergraph_service_status{service_name=\"NGINX\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RESTPP STATUS Primary",
   "type": "stat",
   "description": "GPE status on Prod Pimary cluster",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 107 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "tigergraph_service_status{service_name=\"RESTPP\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "GPE STATUS Primary",
   "type": "stat",
   "description": "ZK status on Prod Pimary cluster",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 112 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "tigergraph_service_status{service_name=\"ZK\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DICT STATUS Primary",
   "type": "stat",
   "description": "GPE status on Prod Pimary cluster",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 117 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "tigergraph_service_status{service_name=\"DICT\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CTRL STATUS Primary",
   "type": "stat",
   "description": "GPE status on Prod Pimary cluster",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 122 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "tigergraph_service_status{service_name=\"CTRL\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}